### PR TITLE
WIP: Optimize cue

### PR DESCRIPTION
**Pull request by moosecanswim**
> NOTE: you will need to use the operator image: `quay.io/greymatterio/operator:kyle-2`

# Optimize Cue
[sc-24607]

There are many changes in this PR:

- restructure of service.cue files
    - move mesh objects out of top level struct and add them to a second tier field, `mesh_config: []`.  Clarifies scope w/ regards to cue.
    - affects `greymatter init`
- abstract redis mesh configs
    - moves the definition of mesh objects into intermediates.cue and removes from any `<service>.cue`
    - affects `greymatter init`
- move oidc out of edge block in input.cue
    - it affects more than just edge so its moved into its own block under defaults in inputs.cue 
    - affects `greymatter init`
- rework tls
    - move spire and tls out from edge and into a tls block.  affects more than just edge and there are implications for both k8s and gm cue files. 
    - affects `greymatter init` and operator

### Restructure service.cue files
In order to allow the requested abstraction or redis out the service.cue files had to change due to the way cue scopes fields vs structs https://cuelang.org/docs/references/spec/#declarations-and-scope.

To be able to re-use a function to generate the required redis configs naming conventions had to be aligned.  When using aliases `let Name=something` the scope was to the file whereas when using a pre-declared identifier `#redis_metrics_mesh_configs` the scope is universal.  To accommodate these differing scopes i forced the scopes by defining them internal to a service.cue's mesh configs field

ex:
```
catalog: {
    let Name: catalog
}
```

### Abstract Redis Mesh Configs

The redis mesh configs have been abstracted out `#redis_mesh_configs` .  To utilize this data we declare an unseen variable and pass it the name of the service
```
  // Creates mesh objects required for redis audits
  _default_redis: #redis_mesh_configs & {
    input: {
      service_name: Name
      // ingress_names: [IngressName]
    }
  },
```

This initializes the _default_redis variable that we can then retrieve the output data with. These "default" redis mesh objects are appended to the end of the `mesh_config` block 

```
catalog:{
    mesh_config:[
        ...
    ] + _default_redis.out.config 
}
```

Additionally, we've added the ability to generate a proxy dynamically utilizing this variable
```
  _dynamic_proxy: #dynamic_proxy_mesh_config & {
    input: {
      service_name: Name
      listener_keys: { [ for mo in mesh_config  if (mo.listener_key != _|_ && mo.domain_keys != _|_) {mo.listener_key} ] }
      domain_keys: { [ for mo in mesh_config  if (mo.domain_key != _|_ && mo.port != _|_) {mo.domain_key} ] }
    }
  },
```

and appending the dynamically created proxy to the mesh configs similar to the redis configs:

```
catalog:{
    mesh_config:[
        ...
    ] +  _default_redis.out.config + _dynamic_proxy.out.config
}
```

> This pattern can be built upon as we abstract more and more generic mesh objects out of service.cue files

### Move OIDC out of Edge Block in Input.cue

Oidc could not be pulled out of input.cue completely because it is used across the project (both in `./k8s/*` and `./gm/*` cue files).  We did pull it out of the edge block because it is not entirely for edge.  It is now in its own block under defaults.

## Rework TLS

TLS has been completely reworked and pulled out of config and edge blocks to be its own thing.  In the `defaults.tls` block you can specify internal and external types and they can be interchangeable
Allowed patterns are:
|  defaults.tls.edge.type | defaults.tls.internal.type |
|-- | -- |
| plaintext | plaintext |
| plaintext | spire |
| tls | plaintext |
| tls | spire |
| tls | manual-certs |

> Note: plaintext edge + manual-certs is not an option.

These allowed configurations are enforced using the new `#TLSSpec` spec.

As part of this work spire configs were moved from their own block to under the tls block.  This required some changes to the operator codes structs so it could unmarshal them.  <Link that PR here>

## Redis Abstraction and Service.cue restructure

To test this start up the mesh like normal using the updated inputs.cue branch.  This should work with no changes to input.cue as with out base installation.  Check the sidecar to ensure it is emitting audits to redis.

## OIDC

- Enable oidc
- Enter configurations and startup mesh
- Configure your keycloak client to redirect to your instance of the mesh
-  When you hit the dashboard you should be prompted to login

## Rework TLS
In the tls block you can set up the following configurations:
- plaintext edge + plaintext internal (default behavior)
- plaintext edge + spire internal
- tls edge + manual-certs internal
- tls edge + spire internal

For "anything + spire": you will need to deploy spire before hand then set default.tls.internal.type to `spire` for the operator to create the spire certs.

For "tls edge + anything": you will need to create a secret with valid certs

For "tls edge + manual-certs" you will need to either reuse the edge tls certs secret (default behavior) or create another secret with certs and set `defaults.tls.internal.manual.secret_name` to the new secret.

### CODE REVIEW

**Comment by moosecanswim** [comment]
@alecholmez @jack-bischoff @danielpcox Looking for your feedback on these changes since i worked with each of you on parts of it.

**Comment by moosecanswim** [comment]
@alecholmez this could also have some ramifications if we wanted to include it in init

**Comment by moosecanswim** [comment]
rabase on main messed it up so wait for a sec

**Comment by alecholmez** [comment]
Okay I'll look at this but I'm going to guess it'll have to be slated for 1.next

We're already feature complete/past code freeze for 1.8

**Comment by danielpcox** [comment]
I'm removing myself as a reviewer here just so it's out of my queue, but perhaps we should close this one if we've decided to do something else? Add me back if you still need a review.

**Comment by tilleryd** [comment]
This has been stale for quite some time and is falling behind. Closing.

**Pull request closed without merging**
